config/routes.rb
Rails.application.routes.draw do
  resources :health_warnings
  root 'pages#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'
  get    '/signup',  to: 'users#new'
  get '/tips/user_tips', to: 'tips#user_tips'

  resources :users
  resources :tips, only: [:show, :create, :destroy]
  resources :lessons, only: [:show, :index] do 
    resources :tips, only: [:index, :new]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :user 
  belongs_to :lesson 
  default_scope -> { order(created_at: :desc) }  #stabby lambda
  validates :user_id, presence: true
  validates :lesson_id, presence: true
  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true 
  #LINK_REGEX = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
  validates :link, presence: true, length: { maximum: 255 }
  #,format: { with: LINK_REGEX }

end

app/controllers/tips_controller.rb
require 'pry'
class TipsController < ApplicationController

  #Nested Routes
  def index
    @tips = Tip.where(:lesson_id => params[:id])
    @lesson = Lesson.find(params[:lesson_id])
  end 

  def user_tips
    @tips = current_user.tips
    render json: @tips, status: 200
  end 

  def new 
     if logged_in?
      @user = current_user
      @tip = Tip.new(:user_id => current_user.id) 
      @lesson = Lesson.find(params[:lesson_id])
      @options = [[@lesson.name, @lesson.id]]
    else 
      redirect_to login_path 
    end 
  end 
#End Nested Routes 

 def show 
  @tip = Tip.find(params[:id])
 end 

  def create
    if logged_in?
    @tip = current_user.tips.build(tip_params)
    if @tip.save
      flash[:success] = "Thanks! Your tip has been added."
      redirect_to root_path
    else
      @options = Lesson.all.map{|l| [l.name, l.id]}    
      @feed_items = []  #The empty array  keeps failed submissions from breaking 
      render 'static_pages/home'
    end
    else
      redirect_to login_path
    end  
  end

  def destroy
    if logged_in?
      @tip = Tip.find(params[:id])
      if @tip.user == current_user
            @tip.destroy
            flash[:success] = "Tip deleted"
      end 
    end 
        redirect_to request.referrer || root_url #request.referrer just redirects to the previous url for a better user experience.

  end

  private

    def tip_params
        params.require(:tip).permit(:title, :description, :link, :lesson_id)
    end

    def correct_user
      @tip = current_user.tips.find_by(id: params[:id])
      redirect_to root_url if @tip.nil?
    end
end

app/views/tips/_tip.html.erb
<li id="tip-<%= tip.id %>"> <!--  opens up the possibility of manipulating individual tips at a future date using JavaScrip -->

  <span class="user"><%= link_to tip.user.name, tip.user %></span>
  <span class="title"><%= tip.title %></span><br>
  <span class="link"><%= tip.link %></span><br>
  <span class="description"><%= tip.description %></span><br>
  <span class="lesson"><%= tip.lesson.name %></span><br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tip.created_at) %> ago.
    <% if current_user?(tip.user) %>
      <%= link_to "delete", tip, method: :delete,
                                       data: { confirm: "Are you sure that you want to delete the tip #{tip.title}?" } %>
    <% end %>
  </span>
</li>

app/views/tips/index.html.erb
<section class="tip_form">
        <h1><%= @lesson.name%></h1>
      <%= link_to "Add tip to this lesson", new_lesson_tip_path %><br>
        <br>
        <ol>

             <%= render @tips %>
        </ol>
      <%= link_to "Add tip to this lesson", new_lesson_tip_path %>
</section>

app/views/tips/new.html.erb
<%=render 'shared/tip_form'%>