config/routes.rb
Rails.application.routes.draw do
  resources :health_warnings
  root 'pages#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'
  get    '/signup',  to: 'users#new'
  get '/tips/user_tips', to: 'tips#user_tips'

  resources :users
  resources :tips, only: [:show, :create, :destroy]
  resources :lessons, only: [:show, :index] do 
    resources :tips, only: [:index, :new]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This page was created by a Flatiron student to help fellow learners and has not been endorsed by the Flatiron School.  
  </small>
  <nav>
    <ul>
   
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
 <div class="container col-lg-8 offset-col-2" >
 <a id="logo" class="navbar-brand" href="#"><span id="slash_slash">//</span>learnHELP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= lessons_path %>">Coding Topics</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= tips_path%>">Best Tips</a>
      </li>
    </ul>
    
    <% if logged_in? %>
    <div id="dropdown_marker" class="block-inline my-2 my-lg-0 dropdown-toggle btn-group navbar-dark"  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <button id="account_icon" class="fa fa-user-circle "></button>
      <div id="test" class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item active nav-item" %>
      </div>
       </div>
    <% else %>
    <div class="block-inline my-2 my-lg-0">
      <button id="icon_header" class="fa fa-sign-in"></button>
    <% end %>
    </div>
    
 
  <div id="login_target"> </div>
  </div>
</nav>

<script>
$(document).ready(function() {
    $("#login_target").append("<%= escape_javascript render 'sessions/form' %>")
   $('#icon_header').click(toggleLoginForm)}); // end ready

</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
     <div class="container">
      <% flash.each do |message_type, message| %> <!--flash = { success: "It worked!", danger: "It failed." }  message type is the key and message is the value-->
        <div class="alert alert-<%= message_type %> mt-2"><%= message %></div>
      <% end %>
        <%= yield %>
        
    </div
  </body>
</html>